services:
#   nginx_jwt:
#     image: nginx
#     ports:
#       - 443:443
#       - 80:80
#     volumes:
#       - ./nginx/conf.d:/etc/nginx/conf.d
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./certs:/etc/nginx/certs
#       - /videos:/videos
#       - ./logs:/etc/nginx/logs
#       - /videos2:/done
#     tty: true
#     restart: unless-stopped
#     environment:
#       - TZ=Asia/Tehran

  flask:
    build: 
      context: ./app
      dockerfile: Dockerfile_1
    ports:
      - 5000:5000
    volumes:
      - ./app/ConvertedVideos:/ConvertedVideos
      - ./app/OriginalVideos:/OriginalVideoVideos
    env_file:
      - ./app/.env

  celery:
    build:
      context: ./app
      dockerfile: Dockerfile_2
    volumes:
      - ./app/ConvertedVideos:/ConvertedVideos
      - ./app/OriginalVideos:/OriginalVideoVideos
    env_file:
      - ./app/.env