services:
  flask:
    build: 
      context: ./app
      dockerfile: Dockerfile_1
    ports:
      - 5000:5000
    volumes:
      - ./app/ConvertedVideos:/app/ConvertedVideos
      - ./app/OriginalVideos:/app/OriginalVideos
    env_file:
      - ./app/.env

  celery:
    build:
      context: ./app
      dockerfile: Dockerfile_2
    volumes:
      - ./app/ConvertedVideos:/app/ConvertedVideos
      - ./app/OriginalVideos:/app/OriginalVideos
    env_file:
      - ./app/.env