services:
  gunicorn:
    build:
      context: ./app
      dockerfile: Dockerfile_1
    # ports:
    #   - 5000:5000
#    user: 1000:1000
    volumes:
      - ./app/done:/app/done
      - ./app/done_symlink/:/app/done_symlink/
      - ./app/OriginalVideos:/app/OriginalVideos
    env_file:
      - ./app/.env
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile_2
#    user: 1000:1000
    volumes:
      - ./app/done:/app/done
      - ./app/done_symlink/:/app/done_symlink/
      - ./app/OriginalVideos:/app/OriginalVideos
      - ./celery:/celery
    env_file:
      - ./app/.env
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./nginx/templates/conf.d/:/etc/nginx/templates/conf.d/
      - ./certs/:/etc/nginx/certs/
      - ./logs/:/etc/nginx/logs/
      - ./app/done/:/app/done/
      - ./app/done_symlink/:/app/done_symlink/
    ports:
      - 443:443
    env_file:
      - ./app/.env
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    depends_on:
      - gunicorn
#volumes:
#  celery:
