# syntax=docker/dockerfile:1
FROM python:slim
WORKDIR /app

# Install ffmpeg and dependencies via apt
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

# Copy application code
COPY . .

# Run gunicorn worker
CMD ["gunicorn","--config", "gunicorn_config.py", "app:app"]