# syntax=docker/dockerfile:1
FROM python:slim
WORKDIR /app
RUN apt-get update && apt-get install -y xz-utils && rm -rf /var/lib/apt/lists/*
ADD https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz /ffmpeg-release.tar.xz
RUN tar -xvf /ffmpeg-release.tar.xz && \
    mv ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/ffmpeg && \
    mv ffmpeg-*-amd64-static/ffprobe /usr/local/bin/ffprobe && \
    chmod +x /usr/local/bin/ffmpeg /usr/local/bin/ffprobe && \
    rm -rf /ffmpeg-release.tar.xz ffmpeg-*-amd64-static
RUN apt-get purge -y xz-utils && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt
COPY . .
CMD ["gunicorn","--config", "gunicorn_config.py", "app:app"]