# syntax=docker/dockerfile:1
FROM python
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*WORKDIR /app
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
COPY . .
CMD ["gunicorn","--config", "gunicorn_config.py", "app:app"]